export const BIKE_BRANDS = [
  "Royal Enfield",
  "KTM",
  "Yamaha",
  "Honda",
  "Bajaj",
  "TVS",
  "Suzuki",
  "Hero",
  "Kawasaki",
  "Triumph",
  "BMW",
  "Jawa",
  "Yezdi",
  "Ducati",
  "Harley-Davidson"
];

export const BIKE_MODELS_BY_BRAND: Record<string, string[]> = {
  "Royal Enfield": [
    "Classic 350",
    "Bullet 350",
    "Himalayan 411",
    "Himalayan 450",
    "Interceptor 650",
    "Continental GT 650",
    "Meteor 350",
    "Hunter 350",
    "Scram 411",
    "Super Meteor 650",
    "Shotgun 650",
    "Classic 500",
    "Bullet 500",
    "Thunderbird 350",
    "Thunderbird 500"
  ],
  "KTM": [
    "Duke 125",
    "Duke 200",
    "Duke 250",
    "Duke 390",
    "RC 125",
    "RC 200",
    "RC 390",
    "Adventure 250",
    "Adventure 390",
    "Duke 790"
  ],
  "Yamaha": [
    "R15 V3",
    "R15 V4",
    "R15S",
    "MT-15",
    "FZ",
    "FZ-S",
    "FZ-X",
    "FZ25",
    "Fazer 25",
    "Aerox 155",
    "R3",
    "MT-03",
    "Fascino 125",
    "RayZR 125"
  ],
  "Honda": [
    "Activa 6G",
    "Activa 125",
    "Shine 125",
    "SP 125",
    "Unicorn",
    "Hornet 2.0",
    "CB200X",
    "H'ness CB350",
    "CB350RS",
    "CB300R",
    "CB300F",
    "CBR650R",
    "Africa Twin",
    "Goldwing"
  ],
  "Bajaj": [
    "Pulsar 125",
    "Pulsar 150",
    "Pulsar 180",
    "Pulsar 220F",
    "Pulsar NS125",
    "Pulsar NS160",
    "Pulsar NS200",
    "Pulsar RS200",
    "Pulsar N160",
    "Pulsar N250",
    "Pulsar F250",
    "Dominar 250",
    "Dominar 400",
    "Avenger 160",
    "Avenger 220",
    "Chetak",
    "Platina",
    "CT 110"
  ],
  "TVS": [
    "Apache RTR 160",
    "Apache RTR 180",
    "Apache RTR 200 4V",
    "Apache RTR 160 4V",
    "Apache RR 310",
    "Apache RTR 310",
    "Raider 125",
    "Ronin",
    "Jupiter",
    "Ntorq 125",
    "iQube",
    "XL 100",
    "Radeon"
  ],
  "Suzuki": [
    "Gixxer",
    "Gixxer SF",
    "Gixxer 250",
    "Gixxer SF 250",
    "V-Strom SX",
    "Access 125",
    "Burgman Street",
    "Avenis",
    "Hayabusa",
    "Katana"
  ],
  "Hero": [
    "Splendor Plus",
    "Passion Pro",
    "Glamour",
    "Xpulse 200 4V",
    "Xpulse 200T",
    "Xtreme 160R",
    "Xtreme 200S",
    "Karizma XMR",
    "Mavrick 440",
    "Destini 125",
    "Pleasure Plus"
  ],
  "Kawasaki": [
    "Ninja 300",
    "Ninja 400",
    "Ninja 650",
    "Ninja 1000SX",
    "ZX-10R",
    "ZX-6R",
    "Z650",
    "Z900",
    "Versys 650",
    "Versys 1000",
    "W175"
  ],
  "Triumph": [
    "Speed 400",
    "Scrambler 400X",
    "Trident 660",
    "Tiger 660",
    "Tiger 900",
    "Tiger 1200",
    "Street Triple R",
    "Street Triple RS",
    "Speed Twin 900",
    "Speed Twin 1200",
    "Bonneville T100",
    "Bonneville T120",
    "Rocket 3"
  ],
  "BMW": [
    "G 310 R",
    "G 310 GS",
    "G 310 RR",
    "S 1000 RR",
    "S 1000 R",
    "S 1000 XR",
    "F 850 GS",
    "F 900 R",
    "R 1250 GS",
    "R 1300 GS",
    "R 18"
  ],
  "Jawa": [
    "Jawa 350",
    "Jawa 42",
    "Jawa 42 Bobber",
    "Jawa Perak"
  ],
  "Yezdi": [
    "Roadster",
    "Scrambler",
    "Adventure"
  ],
  "Ducati": [
    "Monster",
    "Scrambler 800",
    "Multistrada V2",
    "Multistrada V4",
    "Panigale V2",
    "Panigale V4",
    "Streetfighter V2",
    "Streetfighter V4",
    "Diavel V4",
    "DesertX"
  ],
  "Harley-Davidson": [
    "X440",
    "Nightster",
    "Sportster S",
    "Pan America 1250",
    "Fat Boy",
    "Heritage Classic",
    "Street Bob"
  ]
};

export const ALL_MODELS = Object.values(BIKE_MODELS_BY_BRAND).flat().sort();

export const SPARE_PART_CATEGORIES = [
  "All",
  "Engine Oil",
  "Oil Filters",
  "Air Filters",
  "Spark Plugs",
  "Brake Pads",
  "Brake Shoes",
  "Brake Disc",
  "Clutch Plates",
  "Chain & Sprocket",
  "Tires & Tubes",
  "Batteries",
  "Bulbs & Lighting",
  "Mirrors",
  "Levers & Pedals",
  "Control Cables",
  "Gaskets & Seals",
  "Suspension",
  "Bearings",
  "Exhaust Systems",
  "Electrical Components",
  "Body Parts",
  "Riding Gear",
  "Accessories"
];
